apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-genparker-ingress
spec:
  tls:
    - hosts:
        - philanthropy.genparker.com
      secretName: genparker-tls-philanthropy
  rules:
    - host: philanthropy.genparker.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: genparker-philanthropy-svc
                port:
                  number: 59595
