apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  namespace: kafka
  name: postgres-sink-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: 'true'
spec:
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  build:
    output:
      type: docker
      image: ghcr.io/andy2great/postgresdb-sink:latest
      pushSecret: dockersecret
    plugins:
      - name: postgres-plugin
        artifacts:
          - type: maven
            repository: https://repo1.maven.org/maven2
            group: io.debezium
            artifact: debezium-connector-jdbc
            version: 2.5.3.Final
  config:
    group.id: postgres-connect-cluster
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    offset.storage.topic: connect-offsets
    config.storage.topic: connect-configs
    status.storage.topic: connect-status
  template:
    pod:
      imagePullSecrets:
        - name: dockersecret

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  namespace: kafka
  name: connector-postgres-sink
  labels:
    strimzi.io/cluster: postgres-sink-connect-cluster
spec:
  class: io.debezium.connector.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    connection.url: jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:5432/postgres
    connection.username: postgres.kmweqdlgighuhnogorky
    connection.password: 'to Add'
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    insert.mode: upsert
    delete.enabled: true
    primary.key.mode: record_key
    schema.evolution: basic
    database.time_zone: UTC
    topics: genparker-philantropy-topic-data
